/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerScore = IDL.Record({
  'bestDistance' : IDL.Float64,
  'name' : IDL.Text,
  'carIndex' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getPlayersCar' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getTopScores' : IDL.Func([IDL.Nat], [IDL.Vec(PlayerScore)], ['query']),
  'submitScore' : IDL.Func([IDL.Text, IDL.Float64, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerScore = IDL.Record({
    'bestDistance' : IDL.Float64,
    'name' : IDL.Text,
    'carIndex' : IDL.Nat,
  });
  
  return IDL.Service({
    'getPlayersCar' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getTopScores' : IDL.Func([IDL.Nat], [IDL.Vec(PlayerScore)], ['query']),
    'submitScore' : IDL.Func([IDL.Text, IDL.Float64, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };